### ISSUE TITLE
Check for Dependancies 

### ISSUE THREAD

**Issue by tcbutler320** [tcbutler320/ctf-documentor#9]
Cross operating system interoperability is a main goal for this project. Currently, this tool is designed and built for Kali Linux. It does not check for dependencies and therefore does not function as intended in other environments.  

In pursuit of cross-os functionality, the first step is to define the projects dependancies. 

This is a good first issue for hacktoberfest. To close the issue, review the tools used in the main python file and make a dependancies.txt file.

**Comment by OneEyedGhost** [comment]
Can I take up this issue? Do I have to check automator_gui.py only for the dependancies.

**Comment by tcbutler320** [comment]
Absolutely, it’s all yours if your up for it

**Comment by OneEyedGhost** [comment]
Should I keep it in the main folder or a particular folder? Also, should I list the various command to install the dependencies for majorly used OS's? (I'm particularly new so I don't have much knowledge, so any kind of help is awesome)

**Comment by tcbutler320** [comment]
What you sent in is a great start, thanks for the contribution!
